version: '3.1'
services:
  app:
    image: ${IMAGE_NAME}:latest
    build: .
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    restart: always